# Generated by Django 3.1.2 on 2021-02-22 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_product_set', to='store.product')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product_set', to='store.product')),
            ],
        ),
    ]
