# Generated by Django 3.1.2 on 2021-02-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_bundleproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleproduct',
            name='index',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
