# Generated by Django 3.1.2 on 2021-02-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_is_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_variant',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
