# Generated by Django 3.1.2 on 2021-02-22 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_has_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='BundleVariantProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, default=1, null=True)),
                ('bundle_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_variant_set', to='store.bundlevariant')),
                ('included_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_variant_product_set', to='store.product')),
            ],
        ),
    ]
