# Generated by Django 3.1.2 on 2021-02-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_bundlevariant_bundlevariantproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images/products/'),
        ),
    ]
