# Generated by Django 2.2.1 on 2021-04-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_order_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='takeaway',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
