# Generated by Django 2.2.1 on 2021-04-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210413_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='contact',
        ),
    ]
