# Generated by Django 2.2.1 on 2021-04-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20210413_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
