# Generated by Django 2.2.1 on 2021-04-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210413_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymentEnabled',
        ),
    ]
