# Generated by Django 2.2.1 on 2021-04-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
