# Generated by Django 2.2.1 on 2021-04-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20210416_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='use_for_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
