# Generated by Django 2.2.1 on 2021-04-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_order_shipping_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BundleProduct',
            new_name='ListProduct',
        ),
    ]
